/**
 * Kazakh word corpus.
 *
 * Every word is lowercase Cyrillic with an English gloss. Words containing
 * yo, tse, che, shcha, the hard and soft signs, e, yu or ya are deliberately
 * absent: those letters have no counterpart in the 2021 Latin alphabet, and
 * inventing one would teach the wrong spelling. A test enforces this.
 *
 * Difficulty is derived from length rather than hand-tagged, so it can never
 * drift out of sync with the data.
 */

const CORPUS = [
  // Sky, land and weather
  { cy: 'ай', en: 'moon' },
  { cy: 'күн', en: 'sun' },
  { cy: 'тау', en: 'mountain' },
  { cy: 'су', en: 'water' },
  { cy: 'от', en: 'fire' },
  { cy: 'жер', en: 'earth' },
  { cy: 'аспан', en: 'sky' },
  { cy: 'бұлт', en: 'cloud' },
  { cy: 'жел', en: 'wind' },
  { cy: 'қар', en: 'snow' },
  { cy: 'мұз', en: 'ice' },
  { cy: 'бұршақ', en: 'hail' },
  { cy: 'тұман', en: 'fog' },
  { cy: 'жаңбыр', en: 'rain' },
  { cy: 'найзағай', en: 'lightning' },
  { cy: 'көл', en: 'lake' },
  { cy: 'өзен', en: 'river' },
  { cy: 'теңіз', en: 'sea' },
  { cy: 'дала', en: 'steppe' },
  { cy: 'шөл', en: 'desert' },
  { cy: 'орман', en: 'forest' },
  { cy: 'ағаш', en: 'tree' },
  { cy: 'шөп', en: 'grass' },
  { cy: 'гүл', en: 'flower' },
  { cy: 'жапырақ', en: 'leaf' },
  { cy: 'тамыр', en: 'root' },
  { cy: 'тас', en: 'stone' },
  { cy: 'құм', en: 'sand' },
  { cy: 'жол', en: 'road' },
  { cy: 'таң', en: 'dawn' },
  { cy: 'түн', en: 'night' },
  { cy: 'кеш', en: 'evening' },
  { cy: 'таңертең', en: 'morning' },
  { cy: 'жаз', en: 'summer' },
  { cy: 'қыс', en: 'winter' },
  { cy: 'көктем', en: 'spring' },
  { cy: 'күз', en: 'autumn' },
  { cy: 'жұлдыз', en: 'star' },
  { cy: 'көлеңке', en: 'shadow' },
  { cy: 'жайлау', en: 'summer pasture' },
  { cy: 'қыстау', en: 'winter camp' },

  // Animals
  { cy: 'ит', en: 'dog' },
  { cy: 'ат', en: 'horse' },
  { cy: 'қой', en: 'sheep' },
  { cy: 'сиыр', en: 'cow' },
  { cy: 'түйе', en: 'camel' },
  { cy: 'ешкі', en: 'goat' },
  { cy: 'мысық', en: 'cat' },
  { cy: 'тышқан', en: 'mouse' },
  { cy: 'қасқыр', en: 'wolf' },
  { cy: 'түлкі', en: 'fox' },
  { cy: 'аққу', en: 'swan' },
  { cy: 'қаз', en: 'goose' },
  { cy: 'үйрек', en: 'duck' },
  { cy: 'тауық', en: 'hen' },
  { cy: 'құс', en: 'bird' },
  { cy: 'балық', en: 'fish' },
  { cy: 'жылан', en: 'snake' },
  { cy: 'бақа', en: 'frog' },
  { cy: 'көбелек', en: 'butterfly' },
  { cy: 'ара', en: 'bee' },
  { cy: 'құмырсқа', en: 'ant' },
  { cy: 'бүркіт', en: 'eagle' },
  { cy: 'торғай', en: 'sparrow' },
  { cy: 'жылқы', en: 'horses' },
  { cy: 'бота', en: 'camel calf' },
  { cy: 'қозы', en: 'lamb' },
  { cy: 'күшік', en: 'puppy' },
  { cy: 'арыстан', en: 'lion' },
  { cy: 'барыс', en: 'leopard' },
  { cy: 'кірпі', en: 'hedgehog' },
  { cy: 'тиін', en: 'squirrel' },

  // The body
  { cy: 'бас', en: 'head' },
  { cy: 'көз', en: 'eye' },
  { cy: 'құлақ', en: 'ear' },
  { cy: 'мұрын', en: 'nose' },
  { cy: 'ауыз', en: 'mouth' },
  { cy: 'тіс', en: 'tooth' },
  { cy: 'тіл', en: 'tongue' },
  { cy: 'ерін', en: 'lip' },
  { cy: 'шаш', en: 'hair' },
  { cy: 'мойын', en: 'neck' },
  { cy: 'иық', en: 'shoulder' },
  { cy: 'қол', en: 'hand' },
  { cy: 'саусақ', en: 'finger' },
  { cy: 'тізе', en: 'knee' },
  { cy: 'арқа', en: 'back' },
  { cy: 'жүрек', en: 'heart' },
  { cy: 'қан', en: 'blood' },
  { cy: 'сүйек', en: 'bone' },
  { cy: 'бет', en: 'face' },
  { cy: 'маңдай', en: 'forehead' },
  { cy: 'тырнақ', en: 'nail' },

  // People
  { cy: 'ана', en: 'mother' },
  { cy: 'әке', en: 'father' },
  { cy: 'бала', en: 'child' },
  { cy: 'қыз', en: 'girl' },
  { cy: 'ұл', en: 'son' },
  { cy: 'аға', en: 'elder brother' },
  { cy: 'апа', en: 'elder sister' },
  { cy: 'іні', en: 'younger brother' },
  { cy: 'сіңлі', en: 'younger sister' },
  { cy: 'ата', en: 'grandfather' },
  { cy: 'әже', en: 'grandmother' },
  { cy: 'немере', en: 'grandchild' },
  { cy: 'отбасы', en: 'family' },
  { cy: 'туыс', en: 'relative' },
  { cy: 'дос', en: 'friend' },
  { cy: 'көрші', en: 'neighbour' },
  { cy: 'қонақ', en: 'guest' },
  { cy: 'адам', en: 'person' },
  { cy: 'жігіт', en: 'young man' },
  { cy: 'келін', en: 'daughter-in-law' },
  { cy: 'ел', en: 'country' },
  { cy: 'халық', en: 'people' },

  // Food and drink
  { cy: 'нан', en: 'bread' },
  { cy: 'ет', en: 'meat' },
  { cy: 'сүт', en: 'milk' },
  { cy: 'шай', en: 'tea' },
  { cy: 'май', en: 'butter' },
  { cy: 'тұз', en: 'salt' },
  { cy: 'ұн', en: 'flour' },
  { cy: 'бал', en: 'honey' },
  { cy: 'ірімшік', en: 'cheese' },
  { cy: 'қаймақ', en: 'cream' },
  { cy: 'айран', en: 'ayran' },
  { cy: 'қымыз', en: 'kumys' },
  { cy: 'шұбат', en: 'shubat' },
  { cy: 'күріш', en: 'rice' },
  { cy: 'бидай', en: 'wheat' },
  { cy: 'алма', en: 'apple' },
  { cy: 'өрік', en: 'apricot' },
  { cy: 'жүзім', en: 'grape' },
  { cy: 'қарбыз', en: 'watermelon' },
  { cy: 'қауын', en: 'melon' },
  { cy: 'алмұрт', en: 'pear' },
  { cy: 'сарымсақ', en: 'garlic' },
  { cy: 'сәбіз', en: 'carrot' },
  { cy: 'асқабақ', en: 'pumpkin' },
  { cy: 'картоп', en: 'potato' },
  { cy: 'ас', en: 'food' },
  { cy: 'тағам', en: 'dish' },
  { cy: 'сорпа', en: 'broth' },
  { cy: 'бауырсақ', en: 'baursak' },
  { cy: 'палау', en: 'pilaf' },
  { cy: 'дәм', en: 'taste' },
  { cy: 'жеміс', en: 'fruit' },
  { cy: 'көкөніс', en: 'vegetable' },

  // Home and things
  { cy: 'үй', en: 'house' },
  { cy: 'есік', en: 'door' },
  { cy: 'терезе', en: 'window' },
  { cy: 'еден', en: 'floor' },
  { cy: 'қабырға', en: 'wall' },
  { cy: 'төбе', en: 'roof' },
  { cy: 'бөлме', en: 'room' },
  { cy: 'үстел', en: 'table' },
  { cy: 'орындық', en: 'chair' },
  { cy: 'төсек', en: 'bed' },
  { cy: 'жастық', en: 'pillow' },
  { cy: 'көрпе', en: 'blanket' },
  { cy: 'кілем', en: 'carpet' },
  { cy: 'шам', en: 'lamp' },
  { cy: 'шәйнек', en: 'teapot' },
  { cy: 'кесе', en: 'bowl' },
  { cy: 'қасық', en: 'spoon' },
  { cy: 'пышақ', en: 'knife' },
  { cy: 'ыдыс', en: 'dish' },
  { cy: 'айна', en: 'mirror' },
  { cy: 'кілт', en: 'key' },
  { cy: 'қоржын', en: 'saddlebag' },
  { cy: 'сандық', en: 'chest' },
  { cy: 'киіз', en: 'felt' },
  { cy: 'шаңырақ', en: 'yurt crown' },

  // Clothing
  { cy: 'киім', en: 'clothes' },
  { cy: 'көйлек', en: 'dress' },
  { cy: 'шалбар', en: 'trousers' },
  { cy: 'етік', en: 'boots' },
  { cy: 'бөрік', en: 'fur hat' },
  { cy: 'шапан', en: 'robe' },
  { cy: 'белбеу', en: 'belt' },
  { cy: 'орамал', en: 'scarf' },
  { cy: 'шұлық', en: 'sock' },
  { cy: 'қолғап', en: 'glove' },
  { cy: 'тон', en: 'fur coat' },

  // Learning and work
  { cy: 'кітап', en: 'book' },
  { cy: 'дәптер', en: 'notebook' },
  { cy: 'қалам', en: 'pen' },
  { cy: 'мектеп', en: 'school' },
  { cy: 'сынып', en: 'class' },
  { cy: 'сабақ', en: 'lesson' },
  { cy: 'ұстаз', en: 'teacher' },
  { cy: 'оқушы', en: 'pupil' },
  { cy: 'білім', en: 'knowledge' },
  { cy: 'ғылым', en: 'science' },
  { cy: 'сөз', en: 'word' },
  { cy: 'әріп', en: 'letter' },
  { cy: 'сан', en: 'number' },
  { cy: 'есеп', en: 'sum' },
  { cy: 'жазу', en: 'writing' },
  { cy: 'оқу', en: 'reading' },
  { cy: 'жұмыс', en: 'work' },
  { cy: 'кәсіп', en: 'trade' },
  { cy: 'дәрігер', en: 'doctor' },
  { cy: 'инженер', en: 'engineer' },
  { cy: 'мұғалім', en: 'teacher' },
  { cy: 'ақын', en: 'poet' },
  { cy: 'жазушы', en: 'writer' },
  { cy: 'әнші', en: 'singer' },
  { cy: 'аспаз', en: 'cook' },
  { cy: 'диқан', en: 'farmer' },
  { cy: 'малшы', en: 'herder' },
  { cy: 'аңшы', en: 'hunter' },
  { cy: 'балықшы', en: 'fisherman' },
  { cy: 'сатушы', en: 'seller' },
  { cy: 'темірші', en: 'blacksmith' },

  // Culture
  { cy: 'ән', en: 'song' },
  { cy: 'күй', en: 'kuy' },
  { cy: 'домбыра', en: 'dombyra' },
  { cy: 'қобыз', en: 'qobyz' },
  { cy: 'сырнай', en: 'horn' },
  { cy: 'би', en: 'dance' },
  { cy: 'той', en: 'feast' },
  { cy: 'ертегі', en: 'fairy tale' },
  { cy: 'жыр', en: 'epic' },
  { cy: 'дәстүр', en: 'tradition' },
  { cy: 'салт', en: 'custom' },
  { cy: 'мереке', en: 'holiday' },
  { cy: 'наурыз', en: 'Nauryz' },
  { cy: 'бата', en: 'blessing' },
  { cy: 'өнер', en: 'art' },
  { cy: 'сурет', en: 'picture' },
  { cy: 'кесте', en: 'embroidery' },

  // Qualities
  { cy: 'жақсы', en: 'good' },
  { cy: 'жаман', en: 'bad' },
  { cy: 'үлкен', en: 'big' },
  { cy: 'кіші', en: 'small' },
  { cy: 'ұзын', en: 'long' },
  { cy: 'қысқа', en: 'short' },
  { cy: 'биік', en: 'high' },
  { cy: 'аласа', en: 'low' },
  { cy: 'жылы', en: 'warm' },
  { cy: 'суық', en: 'cold' },
  { cy: 'ыстық', en: 'hot' },
  { cy: 'тәтті', en: 'sweet' },
  { cy: 'дәмді', en: 'tasty' },
  { cy: 'таза', en: 'clean' },
  { cy: 'жаңа', en: 'new' },
  { cy: 'ескі', en: 'old' },
  { cy: 'көне', en: 'ancient' },
  { cy: 'бай', en: 'rich' },
  { cy: 'кедей', en: 'poor' },
  { cy: 'батыр', en: 'brave' },
  { cy: 'ақылды', en: 'clever' },
  { cy: 'күшті', en: 'strong' },
  { cy: 'әлсіз', en: 'weak' },
  { cy: 'жас', en: 'young' },
  { cy: 'кәрі', en: 'aged' },
  { cy: 'әдемі', en: 'beautiful' },
  { cy: 'ауыр', en: 'heavy' },
  { cy: 'жеңіл', en: 'light' },
  { cy: 'терең', en: 'deep' },
  { cy: 'кең', en: 'wide' },
  { cy: 'тар', en: 'narrow' },
  { cy: 'дөңгелек', en: 'round' },

  // Inner life
  { cy: 'өмір', en: 'life' },
  { cy: 'өлім', en: 'death' },
  { cy: 'ой', en: 'thought' },
  { cy: 'сезім', en: 'feeling' },
  { cy: 'қуаныш', en: 'joy' },
  { cy: 'мұң', en: 'sorrow' },
  { cy: 'күлкі', en: 'laughter' },
  { cy: 'көңіл', en: 'mood' },
  { cy: 'ұйқы', en: 'sleep' },
  { cy: 'түс', en: 'dream' },
  { cy: 'достық', en: 'friendship' },
  { cy: 'махаббат', en: 'love' },
  { cy: 'бақыт', en: 'happiness' },
  { cy: 'үміт', en: 'hope' },
  { cy: 'арман', en: 'aspiration' },
  { cy: 'намыс', en: 'honour' },
  { cy: 'шындық', en: 'truth' },
  { cy: 'өтірік', en: 'lie' },

  // Time
  { cy: 'уақыт', en: 'time' },
  { cy: 'сағат', en: 'hour' },
  { cy: 'минут', en: 'minute' },
  { cy: 'апта', en: 'week' },
  { cy: 'жыл', en: 'year' },
  { cy: 'бүгін', en: 'today' },
  { cy: 'ертең', en: 'tomorrow' },
  { cy: 'кеше', en: 'yesterday' },
  { cy: 'қазір', en: 'now' },
  { cy: 'әрқашан', en: 'always' },
  { cy: 'кейде', en: 'sometimes' },
  { cy: 'сирек', en: 'rarely' },

  // Numbers
  { cy: 'бір', en: 'one' },
  { cy: 'екі', en: 'two' },
  { cy: 'үш', en: 'three' },
  { cy: 'төрт', en: 'four' },
  { cy: 'бес', en: 'five' },
  { cy: 'алты', en: 'six' },
  { cy: 'жеті', en: 'seven' },
  { cy: 'сегіз', en: 'eight' },
  { cy: 'тоғыз', en: 'nine' },
  { cy: 'он', en: 'ten' },
  { cy: 'жиырма', en: 'twenty' },
  { cy: 'отыз', en: 'thirty' },
  { cy: 'қырық', en: 'forty' },
  { cy: 'елу', en: 'fifty' },
  { cy: 'жүз', en: 'hundred' },
  { cy: 'мың', en: 'thousand' },

  // Colours
  { cy: 'ақ', en: 'white' },
  { cy: 'қара', en: 'black' },
  { cy: 'қызыл', en: 'red' },
  { cy: 'сары', en: 'yellow' },
  { cy: 'көк', en: 'blue' },
  { cy: 'жасыл', en: 'green' },
  { cy: 'күлгін', en: 'purple' },
  { cy: 'қоңыр', en: 'brown' },
  { cy: 'боз', en: 'grey' },

  // Places
  { cy: 'қала', en: 'city' },
  { cy: 'ауыл', en: 'village' },
  { cy: 'көше', en: 'street' },
  { cy: 'базар', en: 'bazaar' },
  { cy: 'дүкен', en: 'shop' },
  { cy: 'аурухана', en: 'hospital' },
  { cy: 'кітапхана', en: 'library' },
  { cy: 'мұражай', en: 'museum' },
  { cy: 'әуежай', en: 'airport' },
  { cy: 'алаң', en: 'square' },
  { cy: 'көпір', en: 'bridge' },
  { cy: 'мұнара', en: 'tower' },
  { cy: 'қорған', en: 'fort' },

  // Direction
  { cy: 'алға', en: 'forward' },
  { cy: 'артқа', en: 'backward' },
  { cy: 'жоғары', en: 'up' },
  { cy: 'төмен', en: 'down' },
  { cy: 'оң', en: 'right' },
  { cy: 'сол', en: 'left' },
  { cy: 'орта', en: 'middle' },
  { cy: 'шет', en: 'edge' },
  { cy: 'жақын', en: 'near' },
  { cy: 'алыс', en: 'far' },

  // Metals
  { cy: 'темір', en: 'iron' },
  { cy: 'алтын', en: 'gold' },
  { cy: 'күміс', en: 'silver' },
  { cy: 'мыс', en: 'copper' },
  { cy: 'жез', en: 'brass' },
  { cy: 'болат', en: 'steel' },

  // Everyday speech
  { cy: 'сәлем', en: 'hello' },
  { cy: 'рахмет', en: 'thank you' },
  { cy: 'кешірім', en: 'pardon' },
  { cy: 'иә', en: 'yes' },
  { cy: 'жоқ', en: 'no' },
  { cy: 'бар', en: 'there is' },
  { cy: 'керек', en: 'needed' },
  { cy: 'мүмкін', en: 'maybe' },
  { cy: 'дұрыс', en: 'correct' },
  { cy: 'қате', en: 'mistake' },
];

export const WORDS = Object.freeze(CORPUS.map((word) => Object.freeze(word)));

/** Difficulty tier 1-3, derived from the number of Cyrillic letters. */
export function tier(word) {
  const length = word.cy.replace(/[\s-]/g, '').length;
  if (length <= 4) return 1;
  if (length <= 6) return 2;
  return 3;
}

/** Every word at or below a difficulty ceiling. */
export function pool(maxTier) {
  return WORDS.filter((word) => tier(word) <= maxTier);
}

/** A random word at or below a difficulty ceiling. */
export function randomWord(maxTier) {
  const candidates = pool(maxTier);
  return candidates[Math.floor(Math.random() * candidates.length)];
}

/**
 * `count` distinct words at or below a difficulty ceiling, in random order.
 * Falls back to repeats only if the pool is smaller than the request.
 */
export function draw(maxTier, count) {
  const candidates = [...pool(maxTier)];
  for (let i = candidates.length - 1; i > 0; i -= 1) {
    const j = Math.floor(Math.random() * (i + 1));
    [candidates[i], candidates[j]] = [candidates[j], candidates[i]];
  }
  const result = candidates.slice(0, count);
  while (result.length < count) {
    result.push(candidates[Math.floor(Math.random() * candidates.length)]);
  }
  return result;
}
